# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the pg gem is defined in your Gemfile
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_development

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
# database: path/to/persistent/storage/production.sqlite3
